In [5]:
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--serial-number', type=str, help='serial number',
                    required=False, default='4206-7KZX-023B')

args, unknown = parser.parse_known_args()  # en lugar de parse_args()
print(args.serial_number)


4206-7KZX-023B


In [6]:
from pprint import pprint

from brainflow.board_shim import BoardShim, BoardIds

board_id = BoardIds.SYNTHETIC_BOARD.value
pprint(BoardShim.get_board_descr(board_id))

{'accel_channels': [17, 18, 19],
 'battery_channel': 29,
 'ecg_channels': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
 'eda_channels': [23],
 'eeg_channels': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
 'eeg_names': 'Fz,C3,Cz,C4,Pz,PO7,Oz,PO8,F5,F7,F3,F1,F2,F4,F6,F8',
 'emg_channels': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
 'eog_channels': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
 'gyro_channels': [20, 21, 22],
 'marker_channel': 31,
 'name': 'Synthetic',
 'num_rows': 32,
 'package_num_channel': 0,
 'ppg_channels': [24, 25],
 'resistance_channels': [27, 28],
 'sampling_rate': 250,
 'temperature_channels': [26],
 'timestamp_channel': 30}


In [7]:
board_id = BoardIds.MUSE_2_BOARD.value
pprint(BoardShim.get_board_descr(board_id))

{'eeg_channels': [1, 2, 3, 4],
 'eeg_names': 'TP9,AF7,AF8,TP10',
 'marker_channel': 7,
 'name': 'Muse2',
 'num_rows': 8,
 'other_channels': [5],
 'package_num_channel': 0,
 'sampling_rate': 256,
 'timestamp_channel': 6}


In [17]:
channel_names = BoardShim.get_board_descr(board_id)['eeg_names'].split(',')
channel_names + ['board_ts','unix_ts']

['TP9', 'AF7', 'AF8', 'TP10', 'board_ts', 'unix_ts']

In [15]:
eeg_channels = BoardShim.get_eeg_channels(board_id)
eeg_channels

[1, 2, 3, 4]

In [16]:
sampling_rate = BoardShim.get_sampling_rate(BoardIds.MUSE_2_BOARD)
sampling_rate

256

In [ ]:
import numpy as np
eps = np.finfo(float).tiny 
np.log()

C:\Users\josee\AppData\Local\Temp\ipykernel_20256\3274798860.py:3: RuntimeWarning: invalid value encountered in log
  np.log(-10)


np.float64(nan)

In [31]:
import numpy as np
np.random.seed(0)

prob = np.random.randint(5, size=4) /4
print(prob)

result = np.where(prob > 0.0000000001, prob, -10)
# print(result)
a = np.log10(result, where=result > 0)
print(result)

[1.   0.   0.75 0.75]
[  1.   -10.     0.75   0.75]


In [32]:
prob

array([1.  , 0.  , 0.75, 0.75])

In [33]:
result

array([  1.  , -10.  ,   0.75,   0.75])

In [34]:
a

array([  0.        , -10.        ,  -0.12493874,  -0.12493874])

In [1]:
{f'COMB{k}': k for k in range(16)}

{'COMB0': 0,
 'COMB1': 1,
 'COMB2': 2,
 'COMB3': 3,
 'COMB4': 4,
 'COMB5': 5,
 'COMB6': 6,
 'COMB7': 7,
 'COMB8': 8,
 'COMB9': 9,
 'COMB10': 10,
 'COMB11': 11,
 'COMB12': 12,
 'COMB13': 13,
 'COMB14': 14,
 'COMB15': 15}