In [1]:
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--serial-number', type=str, help='serial number',
                    required=False, default='4206-7KZX-023B')

args, unknown = parser.parse_known_args()  # en lugar de parse_args()
print(args.serial_number)


4206-7KZX-023B


In [2]:
from pprint import pprint

from brainflow.board_shim import BoardShim, BoardIds

board_id = BoardIds.SYNTHETIC_BOARD.value
pprint(BoardShim.get_board_descr(board_id))

{'accel_channels': [17, 18, 19],
 'battery_channel': 29,
 'ecg_channels': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
 'eda_channels': [23],
 'eeg_channels': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
 'eeg_names': 'Fz,C3,Cz,C4,Pz,PO7,Oz,PO8,F5,F7,F3,F1,F2,F4,F6,F8',
 'emg_channels': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
 'eog_channels': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
 'gyro_channels': [20, 21, 22],
 'marker_channel': 31,
 'name': 'Synthetic',
 'num_rows': 32,
 'package_num_channel': 0,
 'ppg_channels': [24, 25],
 'resistance_channels': [27, 28],
 'sampling_rate': 250,
 'temperature_channels': [26],
 'timestamp_channel': 30}


In [3]:
board_id = BoardIds.MUSE_2_BOARD.value
pprint(BoardShim.get_board_descr(board_id))

{'eeg_channels': [1, 2, 3, 4],
 'eeg_names': 'TP9,AF7,AF8,TP10',
 'marker_channel': 7,
 'name': 'Muse2',
 'num_rows': 8,
 'other_channels': [5],
 'package_num_channel': 0,
 'sampling_rate': 256,
 'timestamp_channel': 6}


In [4]:
channel_names = BoardShim.get_board_descr(board_id)['eeg_names'].split(',')
channel_names + ['board_ts','unix_ts']

['TP9', 'AF7', 'AF8', 'TP10', 'board_ts', 'unix_ts']

In [5]:
eeg_channels = BoardShim.get_eeg_channels(board_id)
eeg_channels

[1, 2, 3, 4]

In [6]:
sampling_rate = BoardShim.get_sampling_rate(BoardIds.MUSE_2_BOARD)
sampling_rate

256

In [7]:
import numpy as np
eps = np.finfo(float).tiny 


In [8]:
import numpy as np
np.random.seed(0)

prob = np.random.randint(5, size=4) /4
print(prob)

result = np.where(prob > 0.0000000001, prob, -10)
# print(result)
a = np.log10(result, where=result > 0)
print(result)

[1.   0.   0.75 0.75]
[  1.   -10.     0.75   0.75]


In [9]:
prob

array([1.  , 0.  , 0.75, 0.75])

In [10]:
result

array([  1.  , -10.  ,   0.75,   0.75])

In [11]:
a

array([ 0.00000000e+000,  1.16369499e-311, -1.24938737e-001,
       -1.24938737e-001])

In [12]:
{f'COMB{k}': k for k in range(16)}

{'COMB0': 0,
 'COMB1': 1,
 'COMB2': 2,
 'COMB3': 3,
 'COMB4': 4,
 'COMB5': 5,
 'COMB6': 6,
 'COMB7': 7,
 'COMB8': 8,
 'COMB9': 9,
 'COMB10': 10,
 'COMB11': 11,
 'COMB12': 12,
 'COMB13': 13,
 'COMB14': 14,
 'COMB15': 15}

In [13]:
relevant_keys = np.arange(0, 400, 400)
relevant_keys

array([0])

In [14]:
np.arange(1,8,3)

array([1, 4, 7])

In [15]:
np.arange(0,512,400)

array([  0, 400])

In [16]:
import pandas as pd
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
c = [9, 10, 11, 12]

d = np.array([a,b,c])
e = pd.DataFrame(d.T,columns=['a','b','c'])
e


a  b   c
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [17]:
# k = e.mean(axis=0)
k = e.mean(axis=0).mean()
k

np.float64(6.5)

In [18]:
e['a'][0]=2
e

C:\Users\josee\AppData\Local\Temp\ipykernel_2548\3536601838.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  e['a'][0]=2


a  b   c
0  2  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [19]:
e[['a','b']]

a  b
0  2  5
1  2  6
2  3  7
3  4  8

In [20]:
score = 1.0 / (1.0 + np.exp(4.0 * 1))
score

np.float64(0.01798620996209156)

In [21]:
a = []
b= [1, 2, 3]
a.append(b)
c

[9, 10, 11, 12]

In [22]:
a


[[1, 2, 3]]

In [23]:
np.zeros([2,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
a = {}

a['pepe'] = 1

In [25]:
a

{'pepe': 1}

In [26]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

scaler = MinMaxScaler(clip=True)
scaler.fit([[0],[10]])   # rango referencia: 0 a 10

# transformar un valor nuevo
val = 50
scaled_val = scaler.transform([[val]])[0][0]
print(scaled_val)  # 0.7


1.0


In [27]:
import itertools

channels = ['TP9','AF7','AF8','TP10']

pairs = list(itertools.product(channels, repeat=2))
pairs = [x[0] + '-' + x[1] for x in pairs]
print(pairs)


['TP9-TP9', 'TP9-AF7', 'TP9-AF8', 'TP9-TP10', 'AF7-TP9', 'AF7-AF7', 'AF7-AF8', 'AF7-TP10', 'AF8-TP9', 'AF8-AF7', 'AF8-AF8', 'AF8-TP10', 'TP10-TP9', 'TP10-AF7', 'TP10-AF8', 'TP10-TP10']


In [28]:
len(pairs)

16